// <auto-generated />
using System;
using AiObservatory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AiObservatory.Data.Migrations
{
    [DbContext(typeof(AiObservatoryDbContext))]
    [Migration("20260825202222_TrackGitHubBackfillCompletion")]
    partial class TrackGitHubBackfillCompletion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AiObservatory.Data.Entities.AdversarialReviewRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ChunkCount")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CostPerAcceptedFinding")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CostUsd")
                        .HasColumnType("numeric");

                    b.Property<long>("InputTokens")
                        .HasColumnType("bigint");

                    b.Property<int>("IssuesAccepted")
                        .HasColumnType("integer");

                    b.Property<int>("IssuesRaised")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("bigint");

                    b.Property<Instant>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Repo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("ReviewDurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Reviewer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("reviewer");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Summary")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAt");

                    b.HasIndex("Reviewer", "Model");

                    b.HasIndex("RunId", "Reviewer", "Role")
                        .IsUnique();

                    b.ToTable("AdversarialReviewRuns", t =>
                        {
                            t.HasCheckConstraint("CK_AdversarialReviewRun_CostUsd_NonNegative", "\"CostUsd\" >= 0");

                            t.HasCheckConstraint("CK_AdversarialReviewRun_InputTokens_NonNegative", "\"InputTokens\" >= 0");

                            t.HasCheckConstraint("CK_AdversarialReviewRun_IssuesAccepted_NonNegative", "\"IssuesAccepted\" >= 0");

                            t.HasCheckConstraint("CK_AdversarialReviewRun_IssuesRaised_NonNegative", "\"IssuesRaised\" >= 0");

                            t.HasCheckConstraint("CK_AdversarialReviewRun_OutputTokens_NonNegative", "\"OutputTokens\" >= 0");
                        });
                });

            modelBuilder.Entity("AiObservatory.Data.Entities.BillingObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BillingPeriod")
                        .HasColumnType("text");

                    b.Property<string>("CostBasis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("CreditAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("GrossAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("ObservationKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Instant>("ObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<LocalDate>("OccurredOn")
                        .HasColumnType("date");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Service")
                        .HasColumnType("text");

                    b.Property<string>("Sku")
                        .HasColumnType("text");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsageScope")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OccurredOn");

                    b.HasIndex("SourceId", "ObservationKey")
                        .IsUnique();

                    b.ToTable("BillingObservations", t =>
                        {
                            t.HasCheckConstraint("CK_BillingObservation_Amounts_Balance", "\"GrossAmount\" + \"CreditAmount\" = \"NetAmount\"");

                            t.HasCheckConstraint("CK_BillingObservation_Billed", "\"CostBasis\" = 'Billed'");

                            t.HasCheckConstraint("CK_BillingObservation_Currency_Normalized", "\"Currency\" ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("CK_BillingObservation_ObservationKey_NonBlank", "btrim(\"ObservationKey\") <> '' AND \"ObservationKey\" = btrim(\"ObservationKey\")");

                            t.HasCheckConstraint("CK_BillingObservation_ProviderApi", "\"SourceKind\" = 'ProviderApi'");

                            t.HasCheckConstraint("CK_BillingObservation_ProviderKey_Normalized", "btrim(\"ProviderKey\") <> '' AND \"ProviderKey\" = btrim(\"ProviderKey\") AND \"ProviderKey\" = lower(\"ProviderKey\")");

                            t.HasCheckConstraint("CK_BillingObservation_SourceId_NonBlank", "btrim(\"SourceId\") <> '' AND \"SourceId\" = btrim(\"SourceId\")");
                        });
                });

            modelBuilder.Entity("AiObservatory.Data.Entities.BudgetRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant?>("LastTriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .HasColumnType("text");

                    b.Property<decimal>("ThresholdUsd")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("BudgetRules");
                });

            modelBuilder.Entity("AiObservatory.Data.Entities.CavemanSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("EstSavedTokens")
                        .HasColumnType("bigint");

                    b.Property<decimal>("EstSavedUsd")
                        .HasColumnType("numeric");

                    b.Property<string>("Mode")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<Instant>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("CavemanSessions", t =>
                        {
                            t.HasCheckConstraint("CK_CavemanSession_EstSavedTokens_NonNegative", "\"EstSavedTokens\" >= 0");

                            t.HasCheckConstraint("CK_CavemanSession_EstSavedUsd_NonNegative", "\"EstSavedUsd\" >= 0");

                            t.HasCheckConstraint("CK_CavemanSession_OutputTokens_NonNegative", "\"OutputTokens\" >= 0");
                        });
                });

            modelBuilder.Entity("AiObservatory.Data.Entities.ClaudeActivitySession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ActiveSeconds")
                        .HasColumnType("bigint");

                    b.Property<Instant>("IngestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Instant>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Project");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.HasIndex("StartedAt");

                    b.ToTable("ClaudeActivitySessions", t =>
                        {
                            t.HasCheckConstraint("CK_ClaudeActivitySession_ActiveSeconds_NonNegative", "\"ActiveSeconds\" >= 0");
                        });
                });

            modelBuilder.Entity("AiObservatory.Data.Entities.CopilotDailyReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("CodeAcceptanceActivityCount")
                        .HasColumnType("bigint");

                    b.Property<long>("CodeGenerationActivityCount")
                        .HasColumnType("bigint");

                    b.Property<string>("CostBasis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DailyActiveUsers")
                        .HasColumnType("integer");

                    b.Property<LocalDate>("Day")
                        .HasColumnType("date");

                    b.Property<int?>("MonthlyActiveUsers")
                        .HasColumnType("integer");

                    b.Property<Instant>("ObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ReportKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsageScope")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UserInitiatedInteractionCount")
                        .HasColumnType("bigint");

                    b.Property<int?>("WeeklyActiveUsers")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Day");

                    b.HasIndex("SourceId", "ReportKey")
                        .IsUnique();

                    b.ToTable("CopilotDailyReports", t =>
                        {
                            t.HasCheckConstraint("CK_CopilotDailyReport_CodeAcceptanceActivityCount_NonNegative", "\"CodeAcceptanceActivityCount\" >= 0");

                            t.HasCheckConstraint("CK_CopilotDailyReport_CodeGenerationActivityCount_NonNegative", "\"CodeGenerationActivityCount\" >= 0");

                            t.HasCheckConstraint("CK_CopilotDailyReport_DailyActiveUsers_NonNegative", "\"DailyActiveUsers\" IS NULL OR \"DailyActiveUsers\" >= 0");

                            t.HasCheckConstraint("CK_CopilotDailyReport_MonthlyActiveUsers_NonNegative", "\"MonthlyActiveUsers\" IS NULL OR \"MonthlyActiveUsers\" >= 0");

                            t.HasCheckConstraint("CK_CopilotDailyReport_NoCost", "\"CostBasis\" = 'None'");

                            t.HasCheckConstraint("CK_CopilotDailyReport_ProviderApi", "\"SourceKind\" = 'ProviderApi'");

                            t.HasCheckConstraint("CK_CopilotDailyReport_Subscription", "\"UsageScope\" = 'Subscription'");

                            t.HasCheckConstraint("CK_CopilotDailyReport_UserInitiatedInteractionCount_NonNegative", "\"UserInitiatedInteractionCount\" >= 0");

                            t.HasCheckConstraint("CK_CopilotDailyReport_WeeklyActiveUsers_NonNegative", "\"WeeklyActiveUsers\" IS NULL OR \"WeeklyActiveUsers\" >= 0");
                        });
                });

            modelBuilder.Entity("AiObservatory.Data.Entities.DailyAggregate", b =>
                {
                    b.Property<LocalDate>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Provider")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("SourceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourceKind")
                        .HasColumnType("text");

                    b.Property<string>("UsageScope")
                        .HasColumnType("text");

                    b.Property<string>("CostBasis")
                        .HasColumnType("text");

                    b.Property<long>("CacheReadTokens")
                        .HasColumnType("bigint");

                    b.Property<decimal>("CacheSavingsUsd")
                        .HasColumnType("numeric");

                    b.Property<long>("CacheWrite1hTokens")
                        .HasColumnType("bigint");

                    b.Property<long>("CacheWriteTokens")
                        .HasColumnType("bigint");

                    b.Property<decimal>("CostUsd")
                        .HasColumnType("numeric");

                    b.Property<long>("InputTokens")
                        .HasColumnType("bigint");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("bigint");

                    b.Property<int>("RequestCount")
                        .HasColumnType("integer");

                    b.Property<int>("UnknownCacheSavingsCount")
                        .HasColumnType("integer");

                    b.Property<int>("UnknownCostCount")
                        .HasColumnType("integer");

                    b.HasKey("Date", "Provider", "Model", "SourceId", "SourceKind", "UsageScope", "CostBasis");

                    b.ToTable("DailyAggregates", t =>
                        {
                            t.HasCheckConstraint("CK_DailyAggregate_CacheReadTokens_NonNegative", "\"CacheReadTokens\" >= 0");

                            t.HasCheckConstraint("CK_DailyAggregate_CacheWrite1hTokens_WithinCacheWrite", "\"CacheWrite1hTokens\" >= 0 AND \"CacheWrite1hTokens\" <= \"CacheWriteTokens\"");

                            t.HasCheckConstraint("CK_DailyAggregate_CacheWriteTokens_NonNegative", "\"CacheWriteTokens\" >= 0");

                            t.HasCheckConstraint("CK_DailyAggregate_CostUsd_NonNegative", "\"CostUsd\" >= 0");

                            t.HasCheckConstraint("CK_DailyAggregate_InputTokens_NonNegative", "\"InputTokens\" >= 0");

                            t.HasCheckConstraint("CK_DailyAggregate_OutputTokens_NonNegative", "\"OutputTokens\" >= 0");

                            t.HasCheckConstraint("CK_DailyAggregate_RequestCount_NonNegative", "\"RequestCount\" >= 0");

                            t.HasCheckConstraint("CK_DailyAggregate_UnknownCostCount_NonNegative", "\"UnknownCostCount\" >= 0");
                        });
                });

            modelBuilder.Entity("AiObservatory.Data.Entities.GitHubBackfillState", b =>
                {
                    b.Property<string>("Repo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("HasCommits")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasPullRequests")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasWorkflowRuns")
                        .HasColumnType("boolean");

                    b.HasKey("Repo");

                    b.ToTable("GitHubBackfillStates");
                });

            modelBuilder.Entity("AiObservatory.Data.Entities.GitHubCommit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Additions")
                        .HasColumnType("integer");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Instant>("CommittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Deletions")
                        .HasColumnType("integer");

                    b.Property<Instant>("IngestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Repo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Sha")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CommittedAt");

                    b.HasIndex("Repo", "Sha")
                        .IsUnique();

                    b.ToTable("GitHubCommits", t =>
                        {
                            t.HasCheckConstraint("CK_GitHubCommit_Additions_NonNegative", "\"Additions\" >= 0");

                            t.HasCheckConstraint("CK_GitHubCommit_Deletions_NonNegative", "\"Deletions\" >= 0");
                        });
                });

            modelBuilder.Entity("AiObservatory.Data.Entities.GitHubPullRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Instant?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("FirstReviewAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("IngestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("MergedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("Repo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Repo", "Number")
                        .IsUnique();

                    b.ToTable("GitHubPullRequests", t =>
                        {
                            t.HasCheckConstraint("CK_GitHubPullRequest_ReviewCount_NonNegative", "\"ReviewCount\" >= 0");
                        });
                });

            modelBuilder.Entity("AiObservatory.Data.Entities.GitHubWorkflowRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("IngestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Repo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("RunId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("WorkflowName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Repo", "RunId")
                        .IsUnique();

                    b.ToTable("GitHubWorkflowRuns");
                });

            modelBuilder.Entity("AiObservatory.Data.Entities.IdeEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentSha256")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("character varying(71)");

                    b.Property<string>("EnvelopeJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Instant>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uuid");

                    b.Property<Instant>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("PartnerId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("IdeEvents");
                });

            modelBuilder.Entity("AiObservatory.Data.Entities.Insight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Instant>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InsightType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<LocalDate>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<LocalDate>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Insights");
                });

            modelBuilder.Entity("AiObservatory.Data.Entities.PricingSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedCatalog")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawEvidence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Instant>("RetrievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("SourceId")
                        .IsUnique()
                        .HasFilter("\"IsActive\"");

                    b.HasIndex("SourceId", "ContentHash")
                        .IsUnique();

                    b.ToTable("PricingSnapshots", t =>
                        {
                            t.HasCheckConstraint("CK_PricingSnapshot_ContentHash_Length", "char_length(\"ContentHash\") = 64");
                        });
                });

            modelBuilder.Entity("AiObservatory.Data.Entities.SourceSyncState", b =>
                {
                    b.Property<string>("SourceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ConsecutiveFailureCount")
                        .HasColumnType("integer");

                    b.Property<long>("ExpectedRefreshIntervalSeconds")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsConfigured")
                        .HasColumnType("boolean");

                    b.Property<Instant?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Instant?>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("LatestObservationAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SourceId");

                    b.ToTable("SourceSyncStates");
                });

            modelBuilder.Entity("AiObservatory.Data.Entities.SpendCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ColorVar")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SpendCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            ColorVar = "--spend-code-review",
                            DisplayName = "Code Review",
                            Key = "code-review",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            ColorVar = "--spend-credits",
                            DisplayName = "Credits",
                            Key = "credits",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            ColorVar = "--spend-ci",
                            DisplayName = "CI",
                            Key = "ci",
                            SortOrder = 30
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111104"),
                            ColorVar = "--spend-subscription",
                            DisplayName = "Subscription",
                            Key = "subscription",
                            SortOrder = 40
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111105"),
                            ColorVar = "--spend-cloud",
                            DisplayName = "Cloud",
                            Key = "cloud",
                            SortOrder = 50
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111106"),
                            ColorVar = "--spend-api-usage",
                            DisplayName = "API Usage",
                            Key = "api-usage",
                            SortOrder = 60
                        });
                });

            modelBuilder.Entity("AiObservatory.Data.Entities.SpendEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AmountGbp")
                        .HasColumnType("numeric");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("CostBasis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EntryKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("FxRate")
                        .HasColumnType("numeric");

                    b.Property<Instant>("ObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<LocalDate>("OccurredOn")
                        .HasColumnType("date");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Instant>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsageScope")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OccurredOn");

                    b.HasIndex("VendorId");

                    b.HasIndex("Source", "EntryKey")
                        .IsUnique()
                        .HasFilter("\"EntryKey\" IS NOT NULL");

                    b.ToTable("SpendEntries", t =>
                        {
                            t.HasCheckConstraint("CK_SpendEntry_AmountGbp_SameSign", "\"Amount\" * \"AmountGbp\" > 0");

                            t.HasCheckConstraint("CK_SpendEntry_Amount_NonZero", "\"Amount\" <> 0");

                            t.HasCheckConstraint("CK_SpendEntry_FxRate_Positive", "\"FxRate\" > 0");
                        });
                });

            modelBuilder.Entity("AiObservatory.Data.Entities.SpendVendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DefaultCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Provider")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DefaultCategoryId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SpendVendors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222201"),
                            DefaultCategoryId = new Guid("11111111-1111-1111-1111-111111111102"),
                            DisplayName = "Anthropic",
                            Key = "anthropic",
                            Provider = "Anthropic"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222202"),
                            DefaultCategoryId = new Guid("11111111-1111-1111-1111-111111111103"),
                            DisplayName = "GitHub Actions",
                            Key = "github-actions"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222203"),
                            DefaultCategoryId = new Guid("11111111-1111-1111-1111-111111111101"),
                            DisplayName = "CodeRabbit",
                            Key = "coderabbit"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222204"),
                            DefaultCategoryId = new Guid("11111111-1111-1111-1111-111111111101"),
                            DisplayName = "Gitar",
                            Key = "gitar"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222205"),
                            DefaultCategoryId = new Guid("11111111-1111-1111-1111-111111111104"),
                            DisplayName = "Moonshot",
                            Key = "moonshot",
                            Provider = "Moonshot"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222206"),
                            DefaultCategoryId = new Guid("11111111-1111-1111-1111-111111111104"),
                            DisplayName = "OpenAI",
                            Key = "openai",
                            Provider = "OpenAI"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222207"),
                            DefaultCategoryId = new Guid("11111111-1111-1111-1111-111111111104"),
                            DisplayName = "Google",
                            Key = "google",
                            Provider = "Google"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222208"),
                            DefaultCategoryId = new Guid("11111111-1111-1111-1111-111111111105"),
                            DisplayName = "Microsoft",
                            Key = "microsoft"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222209"),
                            DefaultCategoryId = new Guid("11111111-1111-1111-1111-111111111104"),
                            DisplayName = "OpenRouter",
                            Key = "openrouter"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222210"),
                            DefaultCategoryId = new Guid("11111111-1111-1111-1111-111111111103"),
                            DisplayName = "Blacksmith",
                            Key = "blacksmith"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222211"),
                            DefaultCategoryId = new Guid("11111111-1111-1111-1111-111111111104"),
                            DisplayName = "GitHub Copilot",
                            Key = "copilot",
                            Provider = "Copilot"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222212"),
                            DefaultCategoryId = new Guid("11111111-1111-1111-1111-111111111104"),
                            DisplayName = "GitHub",
                            Key = "github"
                        });
                });

            modelBuilder.Entity("AiObservatory.Data.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<LocalDate>("ActiveFrom")
                        .HasColumnType("date");

                    b.Property<LocalDate?>("ActiveTo")
                        .HasColumnType("date");

                    b.Property<int>("BillingDay")
                        .HasColumnType("integer");

                    b.Property<decimal>("CostAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("ExtraUsageCost")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("AiObservatory.Data.Entities.UsageEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long?>("CacheReadTokens")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("CacheSavingsUsd")
                        .HasColumnType("numeric");

                    b.Property<long?>("CacheWrite1hTokens")
                        .HasColumnType("bigint");

                    b.Property<long?>("CacheWriteTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("CostBasis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("CostUsd")
                        .HasColumnType("numeric");

                    b.Property<string>("EventKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Instant>("IngestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("InputTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<Instant>("ObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Runtime")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SessionId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("ThoughtTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("UsageScope")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("Provider", "Model")
                        .HasFilter("\"Model\" IS NOT NULL");

                    b.HasIndex("SourceId", "EventKey")
                        .IsUnique()
                        .HasFilter("\"EventKey\" IS NOT NULL");

                    b.ToTable("UsageEvents", t =>
                        {
                            t.HasCheckConstraint("CK_UsageEvent_CacheReadTokens_NonNegative", "\"CacheReadTokens\" IS NULL OR \"CacheReadTokens\" >= 0");

                            t.HasCheckConstraint("CK_UsageEvent_CacheWrite1hTokens_WithinCacheWrite", "\"CacheWrite1hTokens\" IS NULL OR (\"CacheWrite1hTokens\" >= 0 AND \"CacheWrite1hTokens\" <= COALESCE(\"CacheWriteTokens\", 0))");

                            t.HasCheckConstraint("CK_UsageEvent_CacheWriteTokens_NonNegative", "\"CacheWriteTokens\" IS NULL OR \"CacheWriteTokens\" >= 0");

                            t.HasCheckConstraint("CK_UsageEvent_CostUsd_NonNegative", "\"CostUsd\" IS NULL OR \"CostUsd\" >= 0");

                            t.HasCheckConstraint("CK_UsageEvent_InputTokens_NonNegative", "\"InputTokens\" >= 0");

                            t.HasCheckConstraint("CK_UsageEvent_OutputTokens_NonNegative", "\"OutputTokens\" >= 0");

                            t.HasCheckConstraint("CK_UsageEvent_ThoughtTokens_NonNegative", "\"ThoughtTokens\" IS NULL OR \"ThoughtTokens\" >= 0");
                        });
                });

            modelBuilder.Entity("AiObservatory.Data.Entities.SpendEntry", b =>
                {
                    b.HasOne("AiObservatory.Data.Entities.SpendCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AiObservatory.Data.Entities.SpendVendor", null)
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AiObservatory.Data.Entities.SpendVendor", b =>
                {
                    b.HasOne("AiObservatory.Data.Entities.SpendCategory", null)
                        .WithMany()
                        .HasForeignKey("DefaultCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
